"""add theme_color to users

Revision ID: cae63f346775
Revises: 6a0d427969d6
Create Date: 2026-08-03 13:36:03.918396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae63f346775'
down_revision: Union[str, Sequence[str], None] = '6a0d427969d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows with the current green; without it
    # the NOT NULL add fails on a non-empty table.
    op.add_column(
        'users',
        sa.Column(
            'theme_color',
            sa.String(length=7),
            nullable=False,
            server_default='#00ff00',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_color')
    # ### end Alembic commands ###
